[package]
name = "fire-a-rocket"
version = "0.1.0"
authors = ["lopo<lopo@zju.edu.cn>"]
edition = "2021"

[dependencies]
reqwest = { version = "0.11.12", features = ["json"] }
rocket = "0.5.0-rc.2"
tokio = "1.21.2"